const template = document.querySelector('.card-template')
const newCard = template.content.cloneNode(true)
const newCard1 = template.content.cloneNode(true)
const newCard2 = template.content.cloneNode(true)
const newCard3 = template.content.cloneNode(true)
const newCard4 = template.content.cloneNode(true)
const newCard5 = template.content.cloneNode(true)
const newCard6 = template.content.cloneNode(true)
const newCard7 = template.content.cloneNode(true)
const newCard8 = template.content.cloneNode(true)
const newCard9 = template.content.cloneNode(true)
const newCard11 = template.content.cloneNode(true)
const newCard12 = template.content.cloneNode(true)
const list = document.querySelector('.elements-list')
list.prepend(newCard)
list.prepend(newCard1)
list.prepend(newCard2)
list.prepend(newCard3)
list.prepend(newCard4)
list.prepend(newCard5)
list.prepend(newCard6)
list.prepend(newCard7)
list.prepend(newCard8)
list.prepend(newCard9)
list.prepend(newCard11)
list.prepend(newCard12)
